name: Publish

on:
  release:
    types:
      - published

permissions:
  contents: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Build
        run: ./gradlew build
        env:
          COMPACTING_VERSION: ${{ github.event.release.tag_name }}
      - name: Upload release artifact
        uses: softprops/action-gh-release@v1
        with:
          files: build/libs/compacting-drives-${{ github.event.release.tag_name }}.jar
          tag_name: ${{ github.event.release.tag_name }}
      - name: Upload to external sites
        run: ./gradlew curseforge publishModrinth
        env:
          COMPACTING_VERSION: ${{ github.event.release.tag_name }}
          CURSEFORGE: ${{ secrets.CURSEFORGE }}
          MODRINTH: ${{ secrets.MODRINTH }}
